services:
  remark:
    # remove the next line in case you want to use this Docker Compose file separately
    # as otherwise it would complain for absence of Dockerfile
    build: .
    image: ghcr.io/umputun/remark42:latest
    container_name: "comments.example.com" # ‼️ Change this
    hostname: "comments.example.com" # ‼️ Change this
    restart: always
    networks:
      - remark42_tunnel #  which networks to attach the container to

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - 8080

    environment:
      - REMARK_URL=https://comments.example.com # ‼️ Change this
      - SECRET=${SECRET}
      # - TIME_ZONE=America/Edmonton # Default America/Chicago
      - EMOJI=true
      - AUTH_ANON=false # Forbid anonymous commenting
      #
      ## GitHub OAuth
      - ADMIN_SHARED_ID=${ADMIN_SHARED_ID}
      - AUTH_GITHUB_CID=${AUTH_GITHUB_CID}
      - AUTH_GITHUB_CSEC=${AUTH_GITHUB_CSEC}
      #
      ## Google OAuth
      # - AUTH_GOOGLE_CID
      # - AUTH_GOOGLE_CSEC
      #
      ## Facebook OAuth
      # - AUTH_FACEBOOK_CID
      # - AUTH_FACEBOOK_CSEC
      #
      ## Disqus OAuth
      # - AUTH_DISQUS_CID
      # - AUTH_DISQUS_CSEC
      #
      ## ⚠️ Enable it only for the initial comment import or for manual backups.
      # Do not leave the server running with the ADMIN_PASSWD set if you don't have an intention
      # to keep creating backups manually!
      # - ADMIN_PASSWD=${ADMIN_PASSWD}
    volumes:
      - ./var:/srv/var
    env_file:
      - .env

networks:
  remark42_tunnel:
    external: true # tells Compose to use the existing Docker network
