services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cf-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token "${TUNNEL_TOKEN}"
    env_file:
      - .env