services:
  remark:
    # remove the next line in case you want to use this Docker Compose file separately
    # as otherwise it would complain for absence of Dockerfile
    build: .
    image: ghcr.io/umputun/remark42:latest
    container_name: "remark42.example.com"
    hostname: "remark42.example.com"
    restart: always
    networks:
      - cf_tunnel_net #  which networks to attach the container to

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - 8080

    environment:
      - REMARK_URL=https://remark42.example.com # ‼️ Change this
      - SECRET="${SECRET}"
      - AUTH_ANON=false # Forbid anonymous commenting
      - EMOJI=true
      # - TIME_ZONE=America/Edmonton #America/Chicago
      #
      ## GitHub OAuth
      - ADMIN_SHARED_ID="${ADMIN_SHARED_ID}"
      - AUTH_GITHUB_CID="${AUTH_GITHUB_CID}"
      - AUTH_GITHUB_CSEC="${AUTH_GITHUB_CSEC}"
      #
      ## Google OAuth
      # - AUTH_GOOGLE_CID
      # - AUTH_GOOGLE_CSEC
      #
      ## Facebook OAuth
      # - AUTH_FACEBOOK_CID
      # - AUTH_FACEBOOK_CSEC
      #
      ## Disqus OAuth
      # - AUTH_DISQUS_CID
      # - AUTH_DISQUS_CSEC
      #
      ## ⚠️ Enable it only for the initial comment import or for manual backups.
      # Do not leave the server running with the ADMIN_PASSWD set if you don't have an intention
      # to keep creating backups manually!
      # - ADMIN_PASSWD="${ADMIN_PASSWD}"
    volumes:
      - ./var:/srv/var
    env_file:
      - .env

networks:
  cf_tunnel_net:
    external: true # tells Compose to use the existing Docker network
